In [1]:
import pickle

In [4]:
with open('./node_idx/core_cycle_1.pkl', 'rb') as f:
    data = pickle.load(f)

In [7]:
import numpy as np

a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a.shape)
print(a)
print('-'*5)
print(a[[2,1,0]])

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [8]:
f'day_{%d}'.format(1) + 'residual_{%d}'.format(1)

KeyError: '%d'